---
# deployments/ansible/group_vars/app_servers.yml

repo_url: "https://github.com/egayurcel990/banking-peak-load-prototype.git"
docker_compose_version: "v2.29.7"
app_dir: "/home/ubuntu/banking-peak-load-prototype"

app_port: 8080
app_env: production

cache_enabled: "true"
queue_enabled: "true"
rate_limit_enabled: "true"
rate_limit_rps: "1000"
rate_limit_burst: "2000"
circuit_breaker_enabled: "true"
cb_max_failures: "5"
cb_timeout_seconds: "10"

db_read_replica_enabled: "false"
db_primary_dsn: "postgres://postgres:postgres@postgres:5432/banking?sslmode=disable"
pgbouncer_dsn: "postgres://postgres:postgres@pgbouncer:5432/banking?sslmode=disable"
pgbouncer_read_dsn: "postgres://postgres:postgres@pgbouncer:5432/banking?sslmode=disable"

redis_addr: "redis:6379"
cache_balance_ttl: "10s"
cache_tx_status_ttl: "30s"

queue_url: "amqp://guest:guest@rabbitmq:5672/"
queue_workers: "10"

expected_accounts: 100000
expected_transactions: 1000000
