---
# deployments/ansible/group_vars/k6_runners.yml

repo_url: "https://github.com/egayurcel990/banking-peak-load-prototype.git"
docker_compose_version: "v2.29.7"
app_dir: "/home/ubuntu/banking-peak-load-prototype"
