apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: banking

data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: banking

data:
  dashboard.yaml: |
    apiVersion: 1

    providers:
      - name: Banking Peak Load
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.0.2

          ports:
            - containerPort: 3000
              name: http

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"

          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards

            - name: dashboard
              mountPath: /var/lib/grafana/dashboards

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboard
          configMap:
            name: grafana-dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: banking

spec:
  selector:
    app: grafana

  ports:
    - name: http
      port: 3000
      targetPort: http
