apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: banking

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "banking-api"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - banking
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            regex: banking;banking-app;http
            action: keep

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: banking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-discovery
  namespace: banking

rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-discovery
  namespace: banking

subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: banking

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-discovery

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus

      containers:
        - name: prometheus
          image: prom/prometheus:v3.4.0

          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus

          ports:
            - containerPort: 9090
              name: http

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 1
              memory: 1Gi

      volumes:
        - name: config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: banking

spec:
  selector:
    app: prometheus

  ports:
    - name: http
      port: 9090
      targetPort: http
