apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: banking
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: banking

  REDIS_ADDR: redis:6379

  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  DB_PRIMARY_DSN: postgres://postgres:postgres@pgbouncer:6432/banking?sslmode=disable